### ISSUE TITLE
Change NavBar Items for when user is logged in/out

### ISSUE THREAD

**Issue by aalessi18** [seungwookim08/COMP354#42]
As a user, when I am logged in, I should see the following elements on the navigation bar:

**Required**

As a user, when I am logged out, I should see the following elements on the navigation bar:

**Required**

**Task List for Story Completion**
- [x] Code
- [x] Write Test Cases
- [x] Screenshots for UI that you coded
- [x] Any specific diagrams needed to represent your coded (if necessary)
- [x] Unit Testing
- [x] Manual Testing
- [x] UI Validation

**NOTE: Stories can only be placed under Merged with Master Column after functionality, and unit/ui tests are coded**
