### ISSUE TITLE
Remove session information that is stored when a user logs in.

### ISSUE THREAD

**Issue by aalessi18** [seungwookim08/COMP354#44]
When the user logs out, or exits the browser, we need to clear localStorage doing so:

**Requirements**
- "localStorage.clear();"
- This will relate to #42 (NavBar item changes)

**Task List for Story Completion**
- [x] Code
- [x] Write Test Cases
- [x] Screenshots for UI that you coded
- [x] Any specific diagrams needed to represent your coded (if necessary)
- [x] Unit Testing
- [x] Manual Testing
- [x] UI Validation

**NOTE: Stories can only be placed under Merged with Master Column after functionality, and unit/ui tests are coded**
