### ISSUE TITLE
Popup for forget password, once pressed

### ISSUE THREAD

**Issue by aalessi18** [seungwookim08/COMP354#69]
When the user clicks on forget password and is successful, the user should see a popup.

**Required**

**Task List for Story Completion**
- [x] Code
- [ ] Write Test Cases
- [ ] Screenshots for UI that you coded
- [ ] Any specific diagrams needed to represent your coded (if necessary)
- [ ] Unit Testing
- [ ] Manual Testing
- [ ] UI Validation

**NOTE: Stories can only be placed under Merged with Master Column after functionality, and unit/ui tests are coded**
